version: '3.8'

services:
  sifgpt:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./input:/app/input
    restart: unless-stopped
    networks:
      - sifgpt-network

  # Base de datos PostgreSQL (opcional)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=sifgpt
  #     - POSTGRES_USER=sifgpt
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - sifgpt-network

  # Redis para caché (opcional)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - sifgpt-network

  # Nginx como proxy reverso (opcional)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - sifgpt
  #   networks:
  #     - sifgpt-network

volumes:
  postgres_data:

networks:
  sifgpt-network:
    driver: bridge
