name: poc_dd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - aiofiles=23.2.1
  - altair=5.3.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - fastapi=0.111.1
  - ffmpeg=7.0.1
  - filelock=3.15.4
  - flask=3.0.3
  - flask_cors=4.0.0
  - fontconfig=2.14.2
  - fonttools=4.53.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - gmp=6.3.0
  - gnutls=3.7.9
  - gradio=4.41.0
  - gradio-client=1.3.0
  - harfbuzz=9.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.23.4
  - icu=75.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.20
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nettle=3.9.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orjson=3.10.6
  - packaging=24.1
  - pandas=2.2.2
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=4.2.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pygments=2.18.0
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-multipart=0.0.9
  - pytz=2024.1
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.7.1
  - setuptools=71.0.4
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - starlette=0.37.2
  - terminado=0.18.1
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.4
  - typer=0.12.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - uvicorn=0.30.3
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - websockets=11.0.3
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.2.6
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - av==12.3.0
      - coloredlogs==15.0.1
      - ctranslate2==4.3.1
      - distro==1.9.0
      - faster-whisper==1.0.3
      - flatbuffers==24.3.25
      - humanfriendly==10.0
      - mpmath==1.3.0
      - onnxruntime==1.18.1
      - openai==1.36.1
      - protobuf==5.27.2
      - sympy==1.13.1
      - tokenizers==0.19.1
